version: '3'
services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/github-pages:arm64
    environment:
      - JEKYLL_GITHUB_TOKEN=${JEKYLL_GITHUB_TOKEN}
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
    tty: true
